# Numpy and Pandas

## Numpy

### 1D array

In [111]:
import numpy as np


In [2]:
sl=[1,2,3]
np.array(sl)

array([1, 2, 3])

In [3]:
arr=np.array([3,4,5])
arr

array([3, 4, 5])

In [4]:
l=[1,2,3],[3,4,5],[4,5,6]
np.array(l)

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [5]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
np.arange(3,20,4)

array([ 3,  7, 11, 15, 19])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones(6,dtype=int)

array([1, 1, 1, 1, 1, 1])

In [16]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(3,4,5)

array([3.  , 3.25, 3.5 , 3.75, 4.  ])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [19]:
np.random.rand(1,3)

array([[0.9793115 , 0.13632514, 0.50469145]])

In [20]:
np.random.randn(3,5)

array([[-0.04593908,  0.71102875,  0.36154489, -0.33795982, -0.83266619],
       [ 0.64527867,  0.19835077,  1.92210802,  1.06616824,  0.47228689],
       [ 1.74866526,  0.47046123, -2.16577578,  0.76131843, -0.09191669]])

In [21]:
np.random.randint(2,6,7)

array([2, 5, 5, 3, 4, 3, 3])

In [22]:
sa=np.arange(2,10)

In [23]:
sa

array([2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
ra=np.random.randint(0,10,6)

In [25]:
ra

array([2, 3, 9, 9, 4, 5])

In [26]:
sa.min()

2

In [27]:
sa.argmin()

0

In [28]:
sa.max()

9

In [29]:
sa.argmax()

7

In [30]:
ra.max()

9

In [31]:
ra.argmax()

2

In [32]:
sa.dtype

dtype('int32')

In [33]:
ra.dtype

dtype('int32')

In [34]:
a=np.eye(4)

In [35]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
a.dtype

dtype('float64')

In [37]:
a=np.random.rand(3,4)
a

array([[0.53418275, 0.24502233, 0.9073971 , 0.17654512],
       [0.52080142, 0.67346623, 0.35090912, 0.86834027],
       [0.8494114 , 0.48887862, 0.29891814, 0.43646946]])

In [38]:
a.T

array([[0.53418275, 0.52080142, 0.8494114 ],
       [0.24502233, 0.67346623, 0.48887862],
       [0.9073971 , 0.35090912, 0.29891814],
       [0.17654512, 0.86834027, 0.43646946]])

In [39]:
sa=np.arange(10,25)
sa

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
sa=sa.reshape(3,5)

In [41]:
sa

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
sa[2]=100
sa

array([[ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [100, 100, 100, 100, 100]])

In [43]:
sa=np.arange(4,69)
sa

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68])

In [44]:
ssa=sa[5:12]
ssa

array([ 9, 10, 11, 12, 13, 14, 15])

In [45]:
ssa[2:4]=100
ssa

array([  9,  10, 100, 100,  13,  14,  15])

### 2D arrays

In [46]:
m=np.array([[1,2,3],[2,3,4],[3,4,5]])
m

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [47]:
m[2][2]

5

In [48]:
m[:3]

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [49]:
m[:2]

array([[1, 2, 3],
       [2, 3, 4]])

In [50]:
m[1:2,2:3]

array([[4]])

In [51]:
m[1:,2:]

array([[4],
       [5]])

In [53]:
m[1]

array([2, 3, 4])

In [54]:
a=np.arange(1,25)

In [55]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [56]:
a+a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [57]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10])

In [58]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [59]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [60]:
np.max(a)

24

In [61]:
np.min(a)

1

In [62]:
np.argmax(a)

23

In [63]:
np.argmin(a)

0

In [64]:
np.square(a)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576], dtype=int32)

In [65]:
np.std(a)  ##Standard deviation

6.922186552431729

In [66]:
np.var(a) ##variance

47.916666666666664

In [67]:
np.mean(a)

12.5

In [68]:
a=np.random.randn(3,4) ##noraml distribution
a

array([[ 0.82760556, -0.46427734,  0.12710773, -1.39460735],
       [-1.08160546,  1.47561676, -0.33398712,  0.94705842],
       [-1.75638366,  1.40649634, -1.33438682, -0.5449625 ]])

In [69]:
np.round(a,decimals=2)

array([[ 0.83, -0.46,  0.13, -1.39],
       [-1.08,  1.48, -0.33,  0.95],
       [-1.76,  1.41, -1.33, -0.54]])

In [72]:
s=np.array(['a','b','c','a','d','b'])
s

array(['a', 'b', 'c', 'a', 'd', 'b'], dtype='<U1')

In [73]:
np.unique(s)

array(['a', 'b', 'c', 'd'], dtype='<U1')

## Pandas

In [74]:
import pandas as pd

In [75]:
import numpy as np

In [77]:
sp=pd.Series([1,2,3,4],index=['a','b','c','d'])
sp

a    1
b    2
c    3
d    4
dtype: int64

In [78]:
sp2=pd.Series([1,2,3,4],index=['a','c','x','d'])
sp2

a    1
c    2
x    3
d    4
dtype: int64

In [79]:
sp+sp2

a    2.0
b    NaN
c    5.0
d    8.0
x    NaN
dtype: float64

In [81]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(), columns='s1 s2 s3 s4 s5'.split())
df1

s1        s2        s3        s4        s5
A  0.498928  0.045375  0.208187  0.765029  0.146256
B  0.016436  0.967850  0.922399  0.950710  0.874118
C  0.313332  0.173209  0.697058  0.415120  0.594718
D  0.726710  0.880769  0.598782  0.818020  0.067756
E  0.509130  0.626932  0.241117  0.483298  0.407181
F  0.776689  0.274806  0.699754  0.436595  0.206355
G  0.288051  0.168467  0.064267  0.091587  0.863286
H  0.957576  0.066616  0.182699  0.497388  0.559066

In [82]:
df1[['s2','s3']]

s2        s3
A  0.045375  0.208187
B  0.967850  0.922399
C  0.173209  0.697058
D  0.880769  0.598782
E  0.626932  0.241117
F  0.274806  0.699754
G  0.168467  0.064267
H  0.066616  0.182699

In [83]:
df1['s6']=[1,2,3,4,5,6,7,8]

In [84]:
df1

s1        s2        s3        s4        s5  s6
A  0.498928  0.045375  0.208187  0.765029  0.146256   1
B  0.016436  0.967850  0.922399  0.950710  0.874118   2
C  0.313332  0.173209  0.697058  0.415120  0.594718   3
D  0.726710  0.880769  0.598782  0.818020  0.067756   4
E  0.509130  0.626932  0.241117  0.483298  0.407181   5
F  0.776689  0.274806  0.699754  0.436595  0.206355   6
G  0.288051  0.168467  0.064267  0.091587  0.863286   7
H  0.957576  0.066616  0.182699  0.497388  0.559066   8

In [85]:
df1.drop('B')

s1        s2        s3        s4        s5  s6
A  0.498928  0.045375  0.208187  0.765029  0.146256   1
C  0.313332  0.173209  0.697058  0.415120  0.594718   3
D  0.726710  0.880769  0.598782  0.818020  0.067756   4
E  0.509130  0.626932  0.241117  0.483298  0.407181   5
F  0.776689  0.274806  0.699754  0.436595  0.206355   6
G  0.288051  0.168467  0.064267  0.091587  0.863286   7
H  0.957576  0.066616  0.182699  0.497388  0.559066   8

In [86]:
df1.drop('s3',axis=1)

s1        s2        s4        s5  s6
A  0.498928  0.045375  0.765029  0.146256   1
B  0.016436  0.967850  0.950710  0.874118   2
C  0.313332  0.173209  0.415120  0.594718   3
D  0.726710  0.880769  0.818020  0.067756   4
E  0.509130  0.626932  0.483298  0.407181   5
F  0.776689  0.274806  0.436595  0.206355   6
G  0.288051  0.168467  0.091587  0.863286   7
H  0.957576  0.066616  0.497388  0.559066   8

In [87]:
df1.drop(['s2','s4'],axis=1)

s1        s3        s5  s6
A  0.498928  0.208187  0.146256   1
B  0.016436  0.922399  0.874118   2
C  0.313332  0.697058  0.594718   3
D  0.726710  0.598782  0.067756   4
E  0.509130  0.241117  0.407181   5
F  0.776689  0.699754  0.206355   6
G  0.288051  0.064267  0.863286   7
H  0.957576  0.182699  0.559066   8

In [90]:
df2={'a':[1,2,3,4],'b':['a','b','c','d']}
df=pd.DataFrame(df2)
df

a  b
0  1  a
1  2  b
2  3  c
3  4  d

In [91]:
df.drop(2)

a  b
0  1  a
1  2  b
3  4  d

In [92]:
df['a']

0    1
1    2
2    3
3    4
Name: a, dtype: int64

In [93]:
##df=pd.read_csv("name of csv file here")
##df.head() to view 

In [94]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [95]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [101]:
a=np.arange(10,66)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

In [102]:
a=np.arange(65,9,-1) ##Reversing the above array
a

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [108]:
a=np.arange(0,9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [109]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])